main_site = "https://stellarburgers.nomoreparties.site/"
login_site = "https://stellarburgers.nomoreparties.site/login"
register_site = "https://stellarburgers.nomoreparties.site/register"
forgot_password_site = "https://stellarburgers.nomoreparties.site/forgot-password"
profile_site = "https://stellarburgers.nomoreparties.site/account/profile"